"""Agregar columna user.estado2

Revision ID: 83094284c964
Revises: 901df3cb1c79
Create Date: 2022-08-25 20:37:04.248686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83094284c964'
down_revision = '901df3cb1c79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado2')
    # ### end Alembic commands ###
