"""quitar modelo ventas2

Revision ID: b371502c5d49
Revises: e07970e3fe5c
Create Date: 2022-08-30 15:03:45.675529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b371502c5d49'
down_revision = 'e07970e3fe5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venta2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ventas_productos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='venta2_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='venta2_pkey')
    )
    # ### end Alembic commands ###
